---
-   name: Install yum-utils
    yum: name=yum-utils state=latest

-   name: Install docker repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

-   name: Install docker-ce
    yum: name=docker-ce state=latest update_cache=yes
    notify: restart docker

-   name: Enable/Start docker service
    service: name=docker enabled=yes state=started

-   name: Make sure Docker is running
    service: name=docker state=running