---
# Ansible playbook for a datalab server.

- name: Provisioning Jupyterhub
  hosts: 
    - datalab
  vars:
     #Java variables
     java_version: 8
     #java_subversion: 121
     java_set_javahome: true

  roles:
  
  #OS update
    #- role: lab_setup
    
    - docker
    - role: python 
      pyfsrc_version: 3.5.2
      pyfsrc_make_default: yes
      
    - role: jupyterhub
      install_jupyterlab: True
      generate_testusers: True
      gen_test_username:
        - amy
        - joe
        - sue
        - bob
        
    # Rstudio Server
    - role: ansible-oracle-java
    - role: rstudio-server
    #- role: ansible-rstudio
